languageCode = "en-us"
baseURL = "https://atdaycareaurora.com/"
title = "Christian Daycare Aurora"
disableKinds = ["section", "taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
enableGitInfo = true

[build]
writeStats = true
