languageCode = "en-us"
baseURL = "https://atdaycareaurora.com/"
title = "Christian Daycare Aurora"
disableKinds = ["section", "taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
enableGitInfo = true
enableRobotsTXT = true

[build]
  writeStats = true

[params]
  description = "Angelic Treasures focuses on the development of children. Activities are planned on a daily basis to help improve motor development, cognitive skills and overall ..."
#   images = ["site-feature-image.jpg"]
#   title = "My cool site"
