baseURL = "http://example.org/"
languageCode = "en-us"
title = "Christian Daycare Aurora"
disableKinds = ["section", "taxonomy", "page"]
ignoreErrors = ["error-disable-taxonomy"]

[build]
writeStats = true
